CN Edit profile
mugetsu0422/advanced-web-project-frontend pull request #8
Opened 2023-11-12 08:29 UTC by HuynhNguyen0811

2023-11-12 08:47 UTC, mugetsu0422 requested changes
đổi sang tiếng anh đi ô
css của mấy cái input với button copy bên trang signin hoặc singup cho đồng bộ

2023-11-12 08:47 UTC, mugetsu0422 commented on src/account/profile.jsx
> +    console.log('Address:', address);
xóa log

2023-11-12 08:47 UTC, mugetsu0422 commented on src/main.jsx
> +        errorElement: <ErrorPage />,
ở trên có r mà ô

2023-11-12 08:47 UTC, mugetsu0422 commented on src/account/profile.jsx
> +                    type="text"
```suggestion
                    type="number"
```

2023-11-12 12:42 UTC, HuynhNguyen0811 commented on src/account/profile.jsx
> +                    type="text"
tui mới thêm handle ở dưới onchange để bỏ số

2023-11-13 10:17 UTC, mugetsu0422 approved these changes

2023-11-13 12:02 UTC, merged